WITH exploded_tags AS (
    SELECT 
        TICKET_ID,
        TRIM(f.VALUE::STRING) AS TAG,
        TICKET_ASSIGNEE_STATIONS,
        TICKET_FULL_RESOLUTION_TIME_IN_MINUTES,
        TICKET_LATEST_COMMENT_ADDED_TIMESTAMP
    FROM FUNCTIONAL.PRODUCT_SUPPORT.FACT_TICKETS,
    LATERAL FLATTEN(input => TICKET_TAGS) f
    WHERE instance_account_id = 11195643 
        AND TICKET_FULL_RESOLUTION_TIME_IN_MINUTES < 5
        AND CREATED_DATE = '2025-12-08'
        AND TICKET_TAGS IS NOT NULL
        AND TICKET_ASSIGNEE_STATIONS = 0
)
SELECT 
    TICKET_ID,
    TAG,
    TICKET_ASSIGNEE_STATIONS,
    'less than 5 mins' AS TICKET_FULL_RESOLUTION_TIME_IN_MINUTES,
    CASE WHEN TICKET_LATEST_COMMENT_ADDED_TIMESTAMP IS NULL THEN 1 ELSE 0 END AS TICKET_WITHOUT_COMMENTS
FROM exploded_tags
ORDER BY TICKET_ID, TAG
LIMIT 100  -- Optional, adjust as needed
;
