SELECT 
    CASE WHEN TICKET_LATEST_COMMENT_ADDED_TIMESTAMP IS NOT NULL THEN 1 ELSE 0 END AS HAS_ANY_COMMENT,
    CASE WHEN TICKET_LATEST_AGENT_COMMENT_ADDED_TIMESTAMP IS NOT NULL THEN 1 ELSE 0 END AS HAS_AGENT_COMMENT,
    CASE WHEN TICKET_LATEST_PUBLIC_COMMENT_ADDED_TIMESTAMP IS NOT NULL THEN 1 ELSE 0 END AS HAS_PUBLIC_COMMENT,
    COUNT(1) AS TICKET_COUNT,
    ROUND(COUNT(1) * 100.0 / SUM(COUNT(1)) OVER (), 2) AS PERCENTAGE
FROM FUNCTIONAL.PRODUCT_SUPPORT.FACT_TICKETS
WHERE instance_account_id = 11195643 
    AND CREATED_DATE > '2025-09-30'
    AND TICKET_FULL_RESOLUTION_TIME_IN_MINUTES < 60
GROUP BY 1, 2, 3
ORDER BY 4 DESC
