SELECT 
    CASE 
        WHEN TICKET_FULL_RESOLUTION_TIME_IN_MINUTES < 5 THEN '< 5 mins'
        WHEN TICKET_FULL_RESOLUTION_TIME_IN_MINUTES < 60 THEN '< 1 H'
        WHEN TICKET_FULL_RESOLUTION_TIME_IN_MINUTES < 1440 THEN '< 1 D'  -- 24 hours = 1440 mins
        WHEN TICKET_FULL_RESOLUTION_TIME_IN_MINUTES < 7200 THEN '1 to 5 D'  -- 5 days = 7200 mins
        WHEN TICKET_FULL_RESOLUTION_TIME_IN_MINUTES < 14400 THEN '5 to 10 D'  -- 10 days = 14400 mins
        ELSE '> 10 D'
    END AS RESOLUTION_TIME_BUCKET,
    COUNT(1) AS TICKET_COUNT,
    ROUND(COUNT(1) * 100.0 / SUM(COUNT(1)) OVER (), 2) AS PERCENTAGE,

    COUNT(CASE WHEN TICKET_SATISFACTION_SCORE IS NOT NULL THEN 1 END) AS n,
    COUNT(CASE WHEN TICKET_SATISFACTION_SCORE = 5 THEN 1 END) AS COUNT_5_STAR,
    ROUND(
        COUNT(CASE WHEN TICKET_SATISFACTION_SCORE = 5 THEN 1 END) * 100.0 / 
        NULLIF(COUNT(CASE WHEN TICKET_SATISFACTION_SCORE IS NOT NULL THEN 1 END), 0), 
        2
    ) AS CSAT_TOP_BOX_SCORE
FROM FUNCTIONAL.PRODUCT_SUPPORT.FACT_TICKETS
WHERE instance_account_id = 11195643 
    AND CREATED_DATE > '2025-09-30'
GROUP BY 1
ORDER BY 
    CASE 
        WHEN RESOLUTION_TIME_BUCKET = '< 5 mins' THEN 1
        WHEN RESOLUTION_TIME_BUCKET = '< 1 H' THEN 2
        WHEN RESOLUTION_TIME_BUCKET = '< 1 D' THEN 3
        WHEN RESOLUTION_TIME_BUCKET = '1 to 5 D' THEN 4
        WHEN RESOLUTION_TIME_BUCKET = '5 to 10 D' THEN 5
        ELSE 6
    END
