   SELECT 
        TICKET_CHANNEL,
        COUNT(*) as count
    FROM FUNCTIONAL.PRODUCT_SUPPORT.FACT_TICKETS
    WHERE instance_account_id = 11195643 
        --AND TICKET_FULL_RESOLUTION_TIME_IN_MINUTES < 60
        AND CREATED_DATE > '2025-09-30'
        AND TICKET_TAGS IS NOT NULL
    GROUP BY TICKET_CHANNEL
    ORDER BY 2 DESC
